name: BuildApp
on: push
jobs:
    build-project:
        name: Build Project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: install NPM Dependencies
              run: npm install
            - name: Build Project Assets
              run: npm run build
            - name: Fetch Directory path
              run: pwd
            - name: List Contents of the directory  
              run: ls -la
            - name: change directory
              run: cd /home/runner/work/MonkeyDLuffy/MonkeyDLuffy/out
            - name: fetch contents of "out" folder  
              run: ls -la  
            - name: Upload Static Site Content
              uses: actions/upload-artifact@v4
              with:
                name: static-site
                path: /home/runner/work/MonkeyDLuffy/MonkeyDLuffy/out