name: Build-Release-Deploy-App
on: 
  push:
    branches:
      - main
jobs:
  Build-Release-Deploy-project:
    name: Build-Release-Deploy Project
    runs-on: ubuntu-latest
    permissions:
      pages: write
      contents: write
    steps:
      - name: Enable Debug Logging
        run: |
          echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
           ${{ runner.os }}-node-
      - name: install NPM Dependencies
        run: npm install
      - name: Build Project Assets
        run: npm run build
      - name: Verify Directory Structure
        run: |
         pwd
         ls -la
         ls -la ./out
      - name: Prepare GitHub Pages Files (no Jekyll, 404.html for routing)
        run: |
         echo '<script>location.href = "/" + location.pathname + location.search + location.hash;</script>' > ./out/404.html 
      - name: Upload Static Site Content
        uses: actions/upload-artifact@v4
        with:
          name: static-site
          path: /home/runner/work/MonkeyDLuffy/MonkeyDLuffy/out
      - name: Download Site Content
        uses: actions/download-artifact@v4
        with:
          name: static-site
      - name: Archive(zip) the contents of the built artifact
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: "zip"
          filename: "static.zip"
      - name: Create GitHub Release
        id: create_new_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number}}
          release_name: Release ${{ github.run_number}}
      - name: upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_new_release.outputs.upload_url }}
          asset_path: ./static.zip
          asset_name: site-v${{ github.run_number }}.zip
          asset_content_type: application/zip
      - name: Download Release Asset
        uses: robinraju/release-downloader@v1
        with:
          repository: '${{ github.repository }}'
          tag: ${{ github.run_number }}
          filename: site-v${{ github.run_number }}.zip
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: eegg-wwhhiittee.github.io