name: Build & Deploy App
on: 
    push:
        branches:
            - main
jobs:
  Build-Project:
    name: Build & Deploy App
    runs-on: ubuntu-latest
    permissions:
        pages: write
        contents: write
    steps:
      - name: Enable Debug Logging
        run: |
          echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV
          echo "ACTIONS_STEP_DEBUG=true" >> $GITHUB_ENV
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: install NPM Dependencies
        run: npm install
      - name: Build Project Assets
        run: npm run build
      - name: Fetch Directory path
        run: pwd
      - name: Upload Static Site Content
        uses: actions/upload-artifact@v4
        with:
            name: static-site
            path: ./out
      - name: Download Static Site Content
        uses: actions/download-artifact@v4
        with:
            name: static-site
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./out